stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/data.csv
    - src/prepare.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - models/scorecard.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/test.csv
    - models/scorecard.pkl
    - src/evaluate.py
    metrics:
    - metrics.json:
        cache: false
